# Author:  Thomas Laurenson
# Email:   thomas@thomaslaurenson.com
# Website: https://www.thomaslaurenson.com
#
# Description:
# Docker compose for the StarTrek Payroll Web Application
#
# Copyright (c) 2021, Thomas Laurenson
# 
###############################################################################
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################
version: '3'
services:
  mysql:
    image: mysql:5.5
    container_name: startrek_payroll_mysql
    restart: unless-stopped
    environment:
      - MYSQL_PORT="3306"
      - MYSQL_ROOT_PASSWORD="npm"
      - MYSQL_USER="npm"
      - MYSQL_PASSWORD="npm"
      - MYSQL_DATABASE="db"
    volumes:
      - ./mysql/startrek_payroll.sql:/docker-entrypoint-initdb.d/startrek_payroll.sql
    networks:
      - nginxproxy_default

  php:
    image: php:8.0-fpm
    container_name: startrek_payroll_php
    restart: unless-stopped
    build:
      context: php
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - MYSQL_PORT="3306"
      - MYSQL_USER="npm"
      - MYSQL_PASSWORD="npm"
      - MYSQL_DATABASE="db"
    volumes:
      - ./app:/app
    networks:
      - nginxproxy_default

  nginx:
    image: nginx:stable-alpine
    container_name: startrek_payroll_nginx
    restart: unless-stopped
    depends_on:
      - mysql
      - php
    volumes:
      - ./app:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginxproxy_default

networks:
  nginxproxy_default:
    external: true
